### ISSUE TITLE
Push both amd64 & arm64 to ECR public

### ISSUE THREAD

**Issue by andrea-defraia** [PacoVK/tapir#259]
Only amd64 is pushed to public ECR.

I think that editing the current build like this would push both archs to both registries in one go, without having to pull and push:

``` 
     - name: Login to Amazon ECR Public
        id: login-ecr-public
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          AWS_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: o7d8p0l2
          REPOSITORY: tapir
          IMAGE_TAG: latest
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          labels: ${{ steps.meta.outputs.labels }}
```
I haven't tested this but AFAIK it works.
Source: 
https://docs.docker.com/build/ci/github-actions/push-multi-registries/ 
https://github.com/docker/build-push-action/issues/901 

Also, there is no CONTRIBUTING file, should this kind of proposal come from an issue or a PR directly?
