### ISSUE TITLE
How can I get more information to help me deploy tapir?

### ISSUE THREAD

**Issue by WeiMengXS** [PacoVK/tapir#360]
When I try to upload the provider, it returns `{"errorId":"41ede21f-72c9-4df3-a33b-e9f75eea3965","errors":[{"message":"An unexpected error has occurred. Please raise an issue if you think this is a bug."}]`
But based on the existing documents, I haven't been able to find out where the problem lies?

Console output of tapir：
<img width="891" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/cdba3ed8-f1a5-45e5-8bf0-27672ed2916c">
No further information...

**Comment by PacoVK** [comment]
Thanks for reporting! Could you please share further insights? 
Ideally the request you made and the folder structure of your provider, if you tried to push a custom build one.

**Comment by WeiMengXS** [comment]
Hello paco!
Can you help me answer this question?

I got this error while uploading.
`2023-12-25 10:10:16,416 SEVERE [api.map.exc.ThrowableMapper] (executor-thread-3) errorId e8cc5635-4546-4f64-8e88-b816564585a2: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/13909245068916160045/archive/terraform-provider-yunti_0.0.2_darwin_arm64.zip`

I entered the container according to the path and found that the file looked like this:
<img width="540" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/b75defe4-3568-4e4a-abf1-c8a1a0619cbf">
Is there something wrong with my operation?

The directory structure I uploaded is like this:
<img width="869" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/ece67ef4-620f-43ce-bb17-ba72691d327a">

Commands used:
`curl -XPOST --fail-with-body -H 'x-api-key: xxxxxxxx' -F archive=@archive.zip "https://example.com/terraform/providers/v1/fc/yunti/v0.0.2"`

**Comment by PacoVK** [comment]
Assuming that the archive size is `318804492 bytes` (~319MB), did you already set `API_MAX_BODY_SIZE` to a custom value? Because default is 100MB.

**Comment by WeiMengXS** [comment]
Hello, I have set API_MAX_BODY_SIZE to 1GB, but I'm still encountering the same issue even though the file size being uploaded this time is around 50MB.<img width="832" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/50c89665-bd3c-40b9-965b-8db944173566">
-e API_MAX_BODY_SIZE=1024M 
<img width="1725" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/7790bd03-ba37-421d-ba87-ee1e8ef69224">

Commands used:
curl -XPOST --fail-with-body -H 'x-api-key: aZAk6Y6Tu8PhLmcYZnaUN7M7' -F archive=@archive.zip "https://ccb1-14-22-11-165.ngrok-free.app/terraform/providers/v1/fc/yunti/v0.0.2"
Run:
```
docker run -d --name tapir   -p 8088:8080  
-e API_MAX_BODY_SIZE=1024M 
-e BACKEND_CONFIG=elasticsearch   
-e BACKEND_ELASTICSEARCH_HOST=xxxx:9200  
 -e STORAGE_CONFIG=host   
-e REGISTRY_HOSTNAME=localhost  
 -e REGISTRY_PORT=443 
-e REGISTRY_GPG_KEYS_0__ID=xxxx 
-e REGISTRY_GPG_KEYS_0__ASCII_ARMOR=xxxxx 
-e AUTH_ENDPOINT=http://xxxxx:8080/auth/realms/terraform 
-e AUTH_CLIENT_ID=registry 
pacovk/tapir
```

**Comment by PacoVK** [comment]
Ah I think the docs could be more expressive, for the STORAGE_CONFIG. 
You set STORAGE_CONFIG=host which is not valid, to use local volume please set to STORAGE_CONFIG=local

Let me know if that fixes the issue, I will extend the startup script to also check for the storage config and print a better Error message in case it is invalid.

**Comment by WeiMengXS** [comment]
Thank you for your reply.
Oh, sorry for the mistake. However, I have already set STORAGE_CONFIG to local, but the issue still persists. Are there any other directions for troubleshooting?

```
 docker run -d --name tapir   -p 8088:8080  
-e API_MAX_BODY_SIZE=400M 
-e BACKEND_CONFIG=elasticsearch   
-e BACKEND_ELASTICSEARCH_HOST=xxx:9200   
-e STORAGE_CONFIG=local   
-e REGISTRY_HOSTNAME=localhost   
-e REGISTRY_PORT=443 
-e REGISTRY_GPG_KEYS_0__ID=xxx 
-e REGISTRY_GPG_KEYS_0__ASCII_ARMOR=xxx 
-e AUTH_ENDPOINT=http://xxxx:8080/auth/realms/terraform 
-e AUTH_CLIENT_ID=registry 
pacovk/tapir
```

<img width="1725" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/79bf84b4-003b-43eb-8776-8eaae8bd2e2b">
Commands used:

```
$ curl -XPOST  -H 'x-api-key:aZAk6Y6Tu8PhLmcYZnaUN7M7' --fail-with-body  -F archive=@archive.zip https://examlpe.cn/terraform/providers/v1/fc/yunti/v0.0.2
curl: (22) The requested URL returned error: 500
{"errorId":"53b38893-a350-4027-b1ba-81a3a9894435","errors":[{"message":"An unexpected error has occurred. Please raise an issue if you think this is a bug."}]
```

My file:
<img width="679" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/b997daf7-99d0-4fe1-98c8-0d926f12f10c">
The backend files are:
<img width="778" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/1784c152-1fba-473e-9390-4dedcc6ebb41">

**Comment by PacoVK** [comment]
I will try to reproduce and investigate a bit further. Thanks for the comprehensive report👌

**Comment by PacoVK** [comment]
@WeiMengXS  i tried to write a reproducer with the following:
ℹ️ For Keycloak i used my dev setup, but that should not have any influence, since you are already able to login and create the deploykey.
ℹ️  I also did no setup any GPG_ things because you wrote the error occures during upload of the provider. I omitted any setting that is relevant for **downloading** providers to keep it simple

docker-compose.yml
```
version: '3'
services:

  tapir:
    image: pacovk/tapir
    ports:
      - "8088:8080"
    environment:
      API_MAX_BODY_SIZE: 400M
      BACKEND_CONFIG: elasticsearch
      BACKEND_ELASTICSEARCH_HOST: opensearch-node1:9200
      STORAGE_CONFIG: local
      AUTH_ENDPOINT: http://keycloak:8080/realms/tapir

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dev/scripts/keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    command:
      - start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  opensearch-node1:
    image: opensearchproject/opensearch
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - plugins.security.disabled=true
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - "9200:9200" # REST API
      - "9600:9600" # Performance Analyzer
```

I used a fake provider as demo with similar folder structure as you described
I did then the following:
1. create a deploykey via Tapir for the provider, where `namespace=fc` and `type=yunti`
2. issue a upload command to Tapir via curl `curl -XPOST  -H 'x-api-key:tM6pX3IlTBROmLAJk8Nm4Fhy' --fail-with-body  -F archive=@Archiv.zip http://localhost:8088/terraform/providers/v1/fc/yunti/v0.0.2`
3. No error...

I used the following fake provider source: 
[Archiv.zip](https://github.com/PacoVK/tapir/files/13772546/Archiv.zip)

### How to proceed?
* Increase the log level by setting envinroment variable `QUARKUS_LOG_LEVEL=debug`
* Please check if you can upload the "fake provider" i used here.
* If not, please also check if you have any extra setting for Tapir set in your container, apart from those you already posted.
* For further investigation, please try to setup a local Tapir instance from the docker compose reference aforementioned and try to upload your provider there (mind without SSL and GPG you wont be able to **download** but it should at least work with the **upload** 
* Keep me posted here, in case i can further assist i am happy to do so
